services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdevelopmentdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kurrentdb:
    image: kurrentplatform/kurrentdb:25.0.1-experimental-arm64-8.0-jammy # Apple Silicon (M1/M2/M3/M4)
    # image: kurrentplatform/kurrentdb:latest # x86_64/AMD64
    restart: always
    environment:
      KURRENTDB_CLUSTER_SIZE: 1
      KURRENTDB_NODE_PORT: 2113
      KURRENTDB_INSECURE: "true"                  # dev-only: disables TLS & auth
      KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP: "true" # enables Stream Browser in UI
      KURRENTDB_RUN_PROJECTIONS: All
      KURRENTDB_START_STANDARD_PROJECTIONS: "true"
    ports:
      - "2113:2113"
    volumes:
      - kdb_data:/var/lib/kurrentdb

volumes:
  pg_data:
  kdb_data:
